### ISSUE TITLE
Get GAME-INFO and FW requirements option (4-4) no longer works in v0.91x (64 bit)

### ISSUE THREAD

**Issue by doctahoo** [julesontheroad/NSC_BUILDER#74]
Hi,

In your latest 0.9x builds for Windows 64 bits, this feature no longer works. It just does nothing,

Could you have a look into this?

Thank you.

**Comment by julesontheroad** [comment]
Is working for me. Maybe your json files got corrupted since it's using nutdb for some data and dlc names. Try mode 0: Configuration and 4 - Update nutdb to force an update or download the nutdb zip on the master and add it to zconfig.
You can also use the webinterface to get that data. Either way tell me the files that give you an issue because it's working with the ones i tried.

**Comment by doctahoo** [comment]
I'm using version 0.91b currently and I tried updating through option 4 (UPDATE NUTDB), but still does not work. I also tried downloading the nutdb zip file for the zconfig folder, but to no avail. Odd, isn't it?

I know about the new webinterface, but I still find the old option 4 useful and I use it a lot (in v0.89).

In previous 0.89 version, this option works flawlessly.

**Comment by Morozheno** [comment]
> Exception: name 'rom' is not defined
same here

**Comment by julesontheroad** [comment]
Ok, I'll take a better look as soon as I can.

**Comment by julesontheroad** [comment]
Al found it. The issue was in the xci library, the nsp one was working. For the ChromeGui i made a duplicate to make prints with html labels so it was unafected. rom is actually "roma" it was meant to be "roman=roma" because i set romaji as optional in the prints, depending on the config. I'll make a build tomorrow to fix it.

**Comment by doctahoo** [comment]
Thank you for fixing this!

**Comment by doctahoo** [comment]
That's great news! Thank you for fixing this!

**Comment by julesontheroad** [comment]
Should be fixed with latest release:
https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.92

**Comment by doctahoo** [comment]
Yes, it is now fixed!

Thank you soo much!

**Comment by doctahoo** [comment]
Well, I'm sorry to tell you, that the issue still occurs... with nsp updates only! (the FW info option works with base xci and nsp flawlessly).

**Comment by doctahoo** [comment]
Apparently, the issue affects DLCs in nsp format too. (Exception: name 'rom' is not defined)

**Comment by shadowshd** [comment]
Hi,

I can confirm Doctahoo's message, I've got the same "name 'rom' is not defined" with updates in nsp format, everything seems OK with XCI's ;)

Thanks :)

**Comment by julesontheroad** [comment]
Ok, i'll take a look at night again. It will be the same thing probably, I only tested with base nsps and xcis so I missed the error.
0.92b was to fix a bug with compression doesn't fix this btw.

**Comment by julesontheroad** [comment]
Last issue should be fixed now, sorry i left my hdd with the virtual machines i use to build squirrel at work yesterday.
https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.93

**Comment by doctahoo** [comment]
it works great now in the latest release (v0.93 64 bits). Thank you!

**Comment by shadowshd** [comment]
I confirm, it's working good now 👍 

Thanks for this essential tool @julesontheroad 🥇 ;)

**Comment by julesontheroad** [comment]
Cool, thank you guys for the testing. Closing the issue now.
